apache/airavata-php-gateway

app/views/admin/manage-resources.blade.php, public/css/bootstrap-toggle.css, public/js/bootstrap-toggle.js
Enhance Admin Compute Resource Page:
- replace checkboxes with bootstrap toggle buttons
=> switch default toggle buttons to bootstrap toggle buttons

app/controllers/ExperimentController.php, app/libraries/ExperimentUtilities.php
With this fixes, pga can be used to save and launch experiment. with Airavata master code, Airavata master is under development with new data model changes. Only local file transfer is working, therefore there is an limitation for submit experiment with URI format from PGA. if both pga and Airavata server running on same machine this will works(if not please let me know). I tested Echo application and it works fine. Status update functionality is not yet completed.
=> Fixed local experiment create and launch issues with Airavata master

app/controllers/ExperimentController.php, app/libraries/ExperimentUtilities.php, app/libraries/ProjectUtilities.php, app/views/experiment/create-complete.blade.php, app/views/experiment/edit.blade.php, app/views/experiment/summary.blade.php, app/views/partials/experiment-info.blade.php, app/views/partials/experiment-inputs.blade.php, app/views/partials/sharing-form-body.blade.php, app/views/project/edit.blade.php, public/css/sharing.css, public/js/sharing/share.js, public/js/sharing/sharing_utils.js
Experiment sharing is now enabled, with the ability to share at creation time, view privileges on the summary page, and share/edit privileges on the edit page.
=> Experiment Sharing Enabled

app/controllers/ExperimentController.php, app/libraries/ExperimentUtilities.php, app/libraries/ProjectUtilities.php, app/libraries/SharingUtilities.php, app/views/partials/experiment-inputs.blade.php, app/views/partials/sharing-display-body.blade.php, public/css/sharing.css, public/js/sharing/share.js, public/js/sharing/sharing_utils.js
Major Changes:
- Sharing with nobody no longer throws an exception
- Experiments inherit from project permissions at creation
- Cloned experiments inherit all permissions from the original (the user can immediately change those permissions)
- If a user has project permissions revoked, their permissions for all experiments in that project are also revoked
=> Bug Fixes, Project Permissions Inheritance, Clone Experiment Support

app/controllers/ExperimentController.php, app/libraries/ExperimentUtilities.php
- Fixed privilege granting for cloning user
- Ensured that a "users" variable is always passed to experiment-info.blade.php
=> Experiment Clone and Summary View Fixes

app/controllers/ProjectController.php, app/libraries/ExperimentUtilities.php, app/libraries/ProjectUtilities.php, app/views/partials/sharing-display-body.blade.php, public/css/sharing.css, public/js/sharing/share.js, public/js/sharing/sharing_utils.js
- All users may be unshared at once
- Cloning experiment now grants user read access to parent project (but no other experiments in the project)
- JS best practices fixes
- Cosmetic changes
=> Fixes for XSEDE

app/views/partials/sharing-display-body.blade.php, app/views/partials/sharing-form-body.blade.php, public/js/sharing/share.js, public/js/sharing/sharing_utils.js
The sharing UI now updates correctly for load, add, update, and remove operations.
=> Fixed UI Update Issue

app/libraries/ExperimentUtilities.php, app/libraries/ProjectUtilities.php
- New owner is now shared correctly when cloning an experiment
=> fixed adding new owner to cloned experiment

app/views/partials/experiment-info.blade.php, app/views/partials/streaming-data.blade.php, public/js/simstream.js
This update enables websockets data streaming for the OpenMM application.
=> Simstream Integration

app/controllers/ExperimentController.php, app/libraries/Airavata/API/Airavata.php, app/libraries/Airavata/Model/AppCatalog/AppDeployment/Types.php, app/libraries/Airavata/Model/AppCatalog/ComputeResource/Types.php, app/libraries/ExperimentUtilities.php, app/libraries/ProjectUtilities.php, app/routes.php, app/views/partials/experiment-info.blade.php
This pull request fixes bugs that Eroma found during testing of experiment sharing.
This pull request also adds the ability to clone an experiment into a different project.
=> AIRAVATA-2190 Experiment sharing fixes

app/controllers/ExperimentController.php, app/libraries/ExperimentUtilities.php, app/routes.php, app/views/partials/experiment-info.blade.php, app/views/partials/experiment-inputs.blade.php
* make sure only owner of experiment can change the sharing
* also fix the cancel button and routing
=> AIRAVATA-2196 fix experiment sharing

app/views/experiment/summary.blade.php
Previous code had a bug where it would continue checking for a status
change after a status change was detected. This resulted in the page
trying to reload while it was loading, prevent the page from ever
actually loading in some cases.
Also added checking the job status for changes as well.
=> AIRAVATA-2212 Stop checking for status change once detected

app/controllers/ExperimentController.php, app/routes.php, app/views/experiment/create-complete.blade.php, app/views/experiment/edit.blade.php, app/views/experiment/no-sharing-edit.blade.php, app/views/experiment/summary.blade.php, app/views/partials/experiment-info.blade.php, app/views/partials/sharing-display-body.blade.php, app/views/partials/sharing-form-modal.blade.php, app/views/project/create.blade.php, app/views/project/edit.blade.php, public/css/bootstrap.min.css, public/css/sharing.css, public/js/sharing/share.js
This pull request
* updates the sharing UI for launched projects so that changes made are saved via Ajax instead of requiring a second button click.
* improves cloning by showing a modal for picking a project to clone into only when there is more than one project to which the user can write
* prevents autorefreshing when a modal dialog is open
* other general UI improvements like unique button colors and icons
=> AIRAVATA-2228 improvements experiment actions

app/controllers/AdminController.php, app/controllers/UserSettingsController.php, app/libraries/AdminUtilities.php, app/libraries/Airavata/API/Airavata.php, app/libraries/Airavata/Model/AppCatalog/ComputeResource/Types.php, app/libraries/Airavata/Model/Credential/Store/Types.php, app/libraries/Airavata/Model/Group/Types.php, app/libraries/Airavata/Model/Process/Types.php, app/libraries/Airavata/Model/Status/Types.php, app/libraries/URPUtilities.php
Using new CredentialOwnerType to distinguish between credentials created by admins for gateways and credentials created by users for their own compute/storage accounts.
=> AIRAVATA-2232 credential owner type

app/controllers/AdminController.php, app/views/admin/manage-users.blade.php
Some improvements to role management UI
* when user-pending role is added, remove the other roles
* don't allow removing the last role
* other minor bug fixes
=> AIRAVATA-2077 add some validation for user role changing

app/controllers/AdminController.php, app/libraries/AdminUtilities.php, app/libraries/Airavata/API/Airavata.php, app/views/admin/experiment-statistics.blade.php, app/views/admin/manage-experiments.blade.php
Adds three more experiment statistics filtering options to the UI
* username
* application
* hostname
=> AIRAVATA-1792 Implement ability for admin to search for experiments using the created user as well

app/controllers/ExperimentController.php, app/views/experiment/summary.blade.php, app/views/partials/experiment-info.blade.php
Better guards in controller and template code when experiment id can't be loaded for whatever reason.
=> AIRAVATA-2263 Better handling of invalid experiment ids

app/controllers/AdminController.php
The error is displayed on the screen with the previously entered inputs which can be changed and resubmitted.
=> [AIRAVATA-2463] When provider tries to create a Gateway with the same name of an existing Gateway, a meaningful error is displayed

app/controllers/AdminController.php, app/controllers/GatewayRequestUpdateController.php, app/libraries/AdminUtilities.php, app/routes.php, app/views/admin/manage-gateway.blade.php
If there is an error, it is displayed on the modal. If not, it closes and the underlying window refreshes with the success message displayed on refresh.
=> [AIRAVATA-2233] Modal closes and underlying window refreshes every time the update Gateway or create Gateway operations are successful

app/views/admin/manage-gateway.blade.php
Updated the Admin Dashboard to display the CREATED gateways in the Gateway management section.
=> [AIRAVATA-2476] Show CREATED Gateways instead of APPROVED gateways

app/config/email_templates.json, app/controllers/AdminController.php, app/libraries/EmailUtilities.php
Every time there is an update to a particular Gateway, a mail is sent to that Gateway's Provider and the Portal Admin.
=> [AIRAVATA-2473] Mail notification sent to Admin and Gateway Provider

app/libraries/AdminUtilities.php
The identity server password token is generated by storing the username and password provided in the credential store and retrieving the credential store token.
=> [AIRAVATA-2477] Modifying generation of the password token

app/controllers/GatewayRequestUpdateController.php
Updated the method name in GatewayRequestUpdateController.java
=> [AIRAVATA-2481] Resolving the method name

app/controllers/AdminController.php
Removing min:6 characters restriction while admin adds new gateway
=> Removing restriction on username while admin creates gateway

app/controllers/AdminController.php, app/libraries/AdminUtilities.php, app/libraries/CommonUtilities.php
[AIRAVATA-2022] Changing the message displayed after Gateway is requested
[AIRAVATA-2484] Updating the changed admin email while providing the second set of information
=> Minor fixes to pga

app/libraries/IamAdminServicesUtilities.php, app/libraries/Keycloak/Keycloak.php, app/views/admin/manage-users.blade.php
**Users List will now include their First Name, Last Name, Emails and UserNames!**
Issue Status: **Resolved**
=> [AIRAVATA-2444] Added User list with new Fields

app/config/pga_config.php.template, app/controllers/AdminController.php, app/routes.php, app/views/admin/redirect-django.blade.php
Add a re-route page to automatically re route to the new Django portal which can be controlled from pga_config.php
=> Reroute admin module to Django portal.
